# Generated by Django 5.1.6 on 2026-01-06 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_add_categorie_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='annonce',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='annonces_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annonce',
            name='statut_vente',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('vendu', 'Vendu')], default='disponible', max_length=20, verbose_name='Statut de vente'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='telephone_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='ville',
            field=models.CharField(blank=True, help_text="Ville où se trouve l'annonce", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='vues',
            field=models.IntegerField(default=0, help_text="Nombre de vues de l'annonce"),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['-date_publication'], name='annonces_an_date_pu_cf0053_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['status'], name='annonces_an_status_49c294_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['categorie'], name='annonces_an_categor_e8e33a_idx'),
        ),
    ]
