# Generated by Django 5.1.6 on 2026-01-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_alter_annonce_options_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='statut_vente',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('service', 'Service'), ('location', 'Location'), ('autre', 'Autre')], default='disponible', max_length=20, verbose_name="Type d'annonce"),
        ),
    ]
