# Generated by Django 5.1.6 on 2026-01-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_alter_annonce_statut_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Anglais)'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='titre_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre (Anglais)'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='description',
            field=models.TextField(verbose_name='Description (Français)'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre (Français)'),
        ),
    ]
