# Generated by Django 5.1.6 on 2025-02-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
